### ISSUE TITLE
there was a problem with the selected skills response

### ISSUE THREAD

**Issue by flos06** [1337-server/Tracked-media#2]
Hi,
I've followed the instructions but getting a: 'there was a problem with the selected skills response'  message.

The only part in the installation guide that wasn't completely clear to me was what to put as redirect uri in the trakt app. I've put https://layla.amazon.com/api/skill/link/******* in. Linking was also successfull. Any ideas where I could have gone wrong? I've uploaded the lambda folder in the alexa skill app and adjusted the config file. 

I did not create a lambda function as I dont think that is neccessary right?

Edit: I'm an idiot I hosted as JS instead of python. However I am getting: Im having a little trouble try again in a little while.

Edit2: this can be closed I had to put the language of the skill as english UK but the device was english US. Syncing that solved it

**Comment by 1337-server** [comment]
Glad you got it sorted!

**Comment by flos06** [comment]
Not sure if I should open a new issue but I'm getting this response since yesterday:

‘Sorry, Provider is having trouble.’

When trying to add something to my watchlist. It was working before

**Comment by 1337-server** [comment]
Have you check the logs ?

You can check them from the developer pages - > Skill - > Code  -> Cloud watch logs (your region) 

It should have every request send and any error messages.

Was it a movie or series ? what was the name of the title ? sometimes the skill has problems with movies such as 2012, 9, etc.
