### ISSUE TITLE
Alexa Skill Account Link Error to Trakt

### ISSUE THREAD

**Issue by byrozo** [1337-server/Tracked-media#3]
Thank you for the taking the time to put this together and share!  I'm on the last step, trying to link Trakt.tv account from inside my Alexa Skill, but I get an  error:

oauth error
The requested redirect uri is malformed or doesn't match client redirect URI.

I'm using urn:ietf:wg:oauth:2.0:oob in my Trakt API App, which is the only solution I've found to this problem online.  I've been reading Amazon and Trakt OAuth and URI documents, but I can't see what my mistake is.  Is "urn:ietf:wg:oauth:2.0:oob" suppose to be somewhere in the code on Alexa Developer Console?

Any advice would be greatly appreciated!  Excited to get it working.

**Comment by 1337-server** [comment]
Did you add the `Alexa Redirect URLs` from the Account linking page to the trakt app ? 

It should give you 3 URLs on the account linking page in the alexa developer console (its usually at the bottom). You need to add each one to the trakt application you created. You can then click the `Authorize` button. After you save the Trakt app.

**Comment by byrozo** [comment]
Thank you!  First time doing anything like this, I appreciate you taking the time to tell me what I was missing.  Now I just need to figure out why Alexa says error list index out of range!

**Comment by 1337-server** [comment]
You may need to set your defualt list. 

Sometimes not setting a list can cause problems when it tries to add movies or shows. So if you set your list to the watchlist the app should save the default list. I havent managed to find a way around this yet.

**Comment by byrozo** [comment]
I'm sorry, I've been spending days trying to be self sufficient trying to figure this out.  I'm probably over thinking it, like I do, but how do I do that?  When I ask alexa anything other than launch she just give me that error.  Do I need to set the default list in one of the python files?  Thank you so much for your time.

**Comment by 1337-server** [comment]
Did you edit the `lambda/config.py` to add your trakt client id ?

It's this one.
`client_id = "your-api-key-goes-here"`

**Comment by byrozo** [comment]
Yes, that part I at least got!

**Comment by 1337-server** [comment]
Awesome!

You will need to check the logs from the alexa developer console. By default alexa has some great logging built into the console for free.

To view them you need to select the code tab from the developer console, and then you should see `CloudWatch Logs` (you may need to click the down arrow to select the correct region of your amazon device)

Then you can view the logs and it will show all of the errors the device/alexa is having, if you don't understand the logs or have trouble figuring it out. Just let me know, or post the log here and ill look through it.

**Comment by byrozo** [comment]
[Alexa Logs.txt](https://github.com/1337-server/Tracked-media/files/6910518/Alexa.Logs.txt)

Thanks, I opened it up and had no idea what I was looking at.

**Comment by 1337-server** [comment]
This is poor coding on my part. This is happening because the show you are searching for only returned 1 result, and this skill expects at least 3.

Ill try to update the code to fix this as soon as i can.

**Comment by 1337-server** [comment]
The recent commit, might fix this issue but i will need time to fully test this.
